mqtt:
  image: eclipse-mosquitto
  container_name: mosquitto
  restart: always
  entrypoint: /usr/local/sbin/mosquitto -c /etc/mosquitto/mosquitto.conf
  volumes:
    - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    - ./mosquitto/certs/:/etc/mosquitto/certs/
  ports:
    - "1883:1883"
    - "8883:8883"
