version: "3"
services:
  mqtt:
    image: eclipse-mosquitto
    container_name: mosquitto
    restart: on-failure:3
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/certs/:/etc/mosquitto/certs/
    ports:
      - "1883:1883"
      - "8883:8883"
